HOST: http://api.openbookprices.com/

--- OpenBookPrices ---

---
The [OpenBookPrices](http://www.openbookprices.com/) API lets you get current prices
from book vendors around the world, including shipping costs to your country and all
converted into your currency.
---

-- Book Details --

Return very basic details about the book, currently just title and authors. If you want more details here please [create an issue](https://github.com/OpenBookPrices/openbookprices-api/issues) requesting them.
GET /v1/books/{isbn}/details
< 200
< Content-Type: application/json
{
  "authors": [
    "Henry David Thoreau"
  ],
  "title": "Walden",
  "isbn": "9781619493919"
}

-- Book Prices --

Determine the country (and hence currency) of the IP address making the request and then redirect to the specific url.
GET /v1/books/{isbn}/prices
< 302
< Content-Type: text/plain
Redirecting to http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD


Determine the primary currency of the `country` and redirect to the specific url.
GET /v1/books/{isbn}/prices/{country}
< 302
< Content-Type: text/plain
Redirecting to http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD


Return immediately a list of all the vendors who ship to `country` and the pricing details that are currently known.
GET /v1/books/{isbn}/prices/{country}/{currency}
< 200
< Content-Type: application/json
[
  {
    "status": "unfetched",
    "request": {
      "isbn": "9780340831496",
      "country": "US",
      "currency": "USD",
      "vendor": "amazon_uk",
      "url": "http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD/amazon_uk"
    },
    "offers": {},
    "vendor": {
      "code": "amazon_uk",
      "name": "Amazon UK",
      "homepage": "http://www.amazon.co.uk/"
      "url": null
    },
    "meta": {
      "timestamp": 1381517829,
      "ttl": 0,
      "retryDelay": 0.1,
      "preConversionCurrency": null
    }
  },
  {
    "status": "unfetched",
    "request": {
      "isbn": "9780340831496",
      "country": "US",
      "currency": "USD",
      "vendor": "amazon_us",
      "url": "http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD/amazon_us"
    },
    offers: {},
    "vendor": {
      "code": "amazon_us",
      "name": "Amazon USA",
      "homepage": "http://www.amazon.com/",
      "url:" null
    },
    "meta": {
      "timestamp": 1381517829,
      "ttl": 0,
      "retryDelay": 0.1,
      "preConversionCurrency": null
    }
  },
  {
    "status": "unfetched",
    "request": {
      "isbn": "9780340831496",
      "country": "US",
      "currency": "USD",
      "vendor": "foyles",
      "url": "http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD/foyles"
    },
    offers: {},
    "vendor": {
      "code": "foyles",
      "name": "Foyles",
      "homepage": "http://www.foyles.co.uk/",
      "url": null,
    },
    "meta": {
      "timestamp": 1381517829,
      "ttl": 0,
      "retryDelay": 0.1,
      "preConversionCurrency": null
    }
  }
]


Return fresh details for the vendor. If needed this will initiate a fetch of the details so the response may block whilst this is happening.
GET /v1/books/{isbn}/prices/{country}/{currency}/{vendor}
< 200
< Content-Type: application/json
{
  "status": "ok",
  "request": {
    "isbn": "9780340831496",
    "country": "US",
    "currency": "USD",
    "vendor": "amazon_uk",
    "url": "http://api.openbookprices.com/v1/books/9780340831496/prices/US/USD/amazon_uk"
  },
  "offers": {
    "new": {
      "price": 21.7,
      "availabilityNote": "Usually dispatched within 24 hours",
      "shippingNote": "5 to 7 business days",
      "shipping": 6.98,
      "total": 28.68
    }
  },
  "vendor": {
    "code": "amazon_uk",
    "name": "Amazon UK",
    "homepage": "http://www.amazon.co.uk/"
    "url": "http://www.amazon.co.uk/dp/0340831499"
  },
  "meta": {
    "timestamp": 1381518231,
    "ttl": 3600,
    "retryDelay": null,
    "preConversionCurrency": "GBP"
  }
}



-- Ping --

Ping back your own request - useful for checking what the server thinks the time is and what IP address you appear to have. Response is not cached.
GET /ping
< 200
< Content-Type: application/json
{
  "timestamp": 1381509290.302,
  "network": {
    "ip": "12.34.56.78",
    "ips": [
      "12.34.56.78"
    ]
  }
}
