HOST: http://api.openbookprices.com/

--- OpenBookPrices ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Shopping Cart Resources
The following is a section of resources related to the shopping cart
--

Echo back your own request
GET /echo
< 200
< Content-Type: application/json
{
  "timestamp": 1381509290.302,
   "request": {
     "method": "GET",
     "secure": false,
     "protocol": "http",
     "host": "app.openbookprices.com",
       "subdomains": [
     "app"
     ],
     "url": "/",
     "originalUrl": "/echo",
     "path": "/",
     "query": {}
   },
   "network": {
     "ip": "91.235.56.121",
     "ips": [
       "91.235.56.121"
     ]
   },
   "headers": {
     "host": "app.openbookprices.com",
     "user-agent": "Amazon CloudFront",
     "via": "1.0 678cdeea3c67419b8e71d6490af123a1.cloudfront.net (CloudFront)",
     "connection": "Keep-Alive",
     "x-amz-cf-id": "z034Ur0Ub-101_73fuPLKM9wHp-8-ni3qjtRCcA0DdGHpYPtV5Yl0A==",
     "x-forwarded-for": "91.235.56.121",
     "accept-encoding": "gzip",
     "cache-control": ""
   }
}
